### ISSUE TITLE
xcode 14 error

### ISSUE THREAD

**Issue by devops35** [XHMM/react-native-cloud-store#1]
Hello,
I am getting an error like this in xcode 14. How can I solve this?

Stored properties cannot be marked potentially unavailable with '@available'

**Comment by XHMM** [comment]
After having a search, seems this error happened on xcode14beta.
As a workaround, you can build using xcode13 which is compatible with xcode14 as described [here](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1216#issuecomment-1151499928), and I will fix this when possible

**Comment by XHMM** [comment]
Hi, release of `0.5.0-beta` has dropped `@available` usage, you can have a try with `npm i react-native-cloud-store@0.5.0-beta` and wait for your feedback, reopen if still in problem 🙂

**Comment by thenakulgupta** [comment]
Where to run this command: npm i react-native-cloud-store@0.5.0-beta?

**Comment by XHMM** [comment]
> 

run it under you project root, you can alose check [doc](https://react-native-cloud-store.vercel.app/docs/install/with-crna) for details
