### ISSUE TITLE
how to upload content without a local path

### ISSUE THREAD

**Issue by gutenye** [XHMM/react-native-cloud-store#14]
I want to upload the content directly to iCloud, something like `upload(cloudPath, content, { onProgress })`,  basically a version of `writeFile + onProgress`, without the need to create a temporary file, but also support `onProgress` callback. 

I believe this is a very common case, is there a method to do it? Thanks

**Comment by XHMM** [comment]
Currently you need to do as you said.

I will add onProgress support for writeFile next version, and thanks for your suggestion.
________________________________
发件人: Guten Ye ***@***.***>
发送时间: Thursday, March 2, 2023 5:01:04 PM
收件人: XHMM/react-native-cloud-store ***@***.***>
抄送: Subscribed ***@***.***>
主题: [XHMM/react-native-cloud-store] how to upload content without a local path (Issue #14)


I want to upload the content directly to iCloud, something like upload(cloudPath, content, { onProgress }), basically a version of writeFile + onProgress, without the need to create a temporary file, but also support onProgress callback.

I believe this is a very common case, is there a method to do it? Thanks

―

**Comment by XHMM** [comment]
supported in [v0.10.0](https://github.com/XHMM/react-native-cloud-store/releases/tag/0.10.0)
