### ISSUE TITLE
Placeholder .fileName.txt.icloud iOS 17 problem

### ISSUE THREAD

**Issue by psquizzle** [XHMM/react-native-cloud-store#18]
In iOS 17 calling cloudReadDirectoryAsync("dirURI"), no longer returns placeholder paths (e.g. .fileName.txt.icloud) in iOS 17 if the file is not downloaded. This prevents the shortcut to quickly decide if the file needs to be downloaded by checking for this filename pattern. Calling stat() on each file is not an option as this is far slower for a large number of files. Are you aware of this change in behavior? Is there any other way to quickly determine if a file has been downloaded within iOS API's?

**Comment by XHMM** [comment]
I haven't tried iOS 17 as it's not stable now.  
Using file pattern to determine download status is not a reliable way, you may have to use `stat()` currently
