### ISSUE TITLE
The file “xyz.abc” couldn’t be opened because URL type https isn’t supported.

### ISSUE THREAD

**Issue by rskapadiadev** [XHMM/react-native-cloud-store#2]
I want to upload file to iCloud the file is http url link
How can i upload it ?

**Comment by XHMM** [comment]
This repo not support http resource, you need to :
1. download file manually to local folder using such as [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob) 
2. use `upload("file:///your/path/to/local/file",  "cloudpath")` to upload

**Comment by rskapadiadev** [comment]
Thanks @XHMM 
Its work

**Comment by rskapadiadev** [comment]
@XHMM But package should support this HTTP upload
Lets see in future for expansion

**Comment by XHMM** [comment]
> 

Thanks for your feedback, I will add it to future plans
