### ISSUE TITLE
folder not exists, you need create it first

### ISSUE THREAD

**Issue by avaghasiya-supra** [XHMM/react-native-cloud-store#20]
I am saving a file from my app to iCloud Drive. So it's working as expected. It's creating my app folder with saved files in the iCloud Drive app.

But if I delete the folder and try to save the file again from my app, it gives an error [Error: folder of "/private/var/mobile/Library/Mobile Documents/iCloud~com~xxx~xxx/Documents" not exists, you need create it first].

How to fix this issue?
Thanks in advance.

**Comment by XHMM** [comment]
Did you delete the 'Documents' directory?,  you need to create the parent directory first and then save it.

**Comment by avaghasiya-supra** [comment]
yes delete and create a new and it's working
