### ISSUE TITLE
[iOS]onProgress is not called when download ".cloud" file

### ISSUE THREAD

**Issue by YaoHuiJi** [XHMM/react-native-cloud-store#21]
hi, I don't know if I'm using the api wrong or if this is a bug, I try to download a ".icloud" file and wait until it's downloaded, but it seems like the onProgress func is never be called. Here are the code pieces in my project.

This is the code used to register globalDownloadEvent to support onProgress:
```
export const useCloudOnProgress = () => {
  useEffect(() => {
    const r1 = CloudStore.registerGlobalDownloadEvent();
    const r2 = CloudStore.registerGlobalUploadEvent();

    return () => {
      r1?.remove();
      r2?.remove();
    };
  }, []);
};
```
onProgress works well when uploading file, but not when downloading file.

This is the code used to download file:
```
export const downloadAndWait = async cloudFilePath => {
  return new Promise((resolve, reject) => {
    CloudStore.download(cloudFilePath, {
      onProgress: data => {
        console.log('onProgress called:', data);
        if (data.progress === 100) {
          console.log('downloaded');
          resolve(true);
        }
      },
    })
      .then(() => {
        console.log('try to download file');
      })
      .catch(err => {
        console.log('failed to download');
        reject(err);
      });
  });
};
```

call downloadAndWait:
```
 downloadAndWait(".xxxx.xxx.icloud")
            .then(() => {
              console.log('downloadAndWait->ok');
            })
            .catch(err => {
              console.log('downloadAndWait->failed：', err);
            })
            .finally(() => {
              console.log('downloadAndWait->done');
            });
```

after downloadAndWait is called, I can only see  "try download file" in the terminal, nothing else,  it seems the Promise is not settled because onProgress is not called and no error either.

### Environments:
"react-native": "0.72.4"
"react-native-cloud-store": "^0.10.3",

**Comment by psquizzle** [comment]
#16

**Comment by XHMM** [comment]
Please try the `0.10.4`, it may fix the issue.

**Comment by YaoHuiJi** [comment]
@XHMM It works now, tested on iOS 15.7.9 & 16.7, thank you for your great work!
