### ISSUE TITLE
Need to declare privacy manifest files

### ISSUE THREAD

**Issue by williamliangwl** [XHMM/react-native-cloud-store#28]
Hi,

we recently uploaded our app to App Store and we receive a feedback like this 

> ITMS-91053: Missing API declaration - Your app’s code references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

Upon using search feature in XCode, I can see this library is using some APIs mentioned in the Apple's link and the link also states that the 3rd party SDK need to declare its own privacy manifest file

so we need your help on this

**Comment by XHMM** [comment]
Thanks for your feedback, I will have a check soon

**Comment by XHMM** [comment]
Privacy manifest has been added, you can try the latest version(v0.12.0)
