### ISSUE TITLE
Build issue with Expo

### ISSUE THREAD

**Issue by psquizzle** [XHMM/react-native-cloud-store#7]
So I have followed the setup instructions in the docs. Including steps in XCode. Container is set up iCloudContainerEnvironment: Development is in the info.plist. The build gets to the end of Fastlane and throws the following error:

 Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key "iCloudContainerEnvironment": expected one of {Development, Production}, but no value was provided" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key "iCloudContainerEnvironment": expected one of {Development, Production}, but no value was provided}

Any ideas on how to fix this error?

**Comment by XHMM** [comment]
I haven't tried buidling expo with fastlane, but I will try it when available.

Didi you tried manually add this to `xx.entitlement`:
```
<key>com.apple.developer.icloud-container-environment</key>
<string>Production</string>
```
and then run build ?

**Comment by psquizzle** [comment]
It worked, and the build was successful! Just add this key-value pair to your [appname]. entitlements file located in 'ios/appname/' folder

**Comment by XHMM** [comment]
Thanks for your feedback,  I will fix this soon 😄
________________________________
发件人: psquizzle ***@***.***>
发送时间: Monday, November 28, 2022 11:24:24 PM
收件人: XHMM/react-native-cloud-store ***@***.***>
抄送: xiao xin ***@***.***>; Comment ***@***.***>
主题: Re: [XHMM/react-native-cloud-store] Build issue with Expo (Issue #7)


It worked build was successful! Just add this key-value pair to your [appname]. entitlements file located in 'ios/appname/' folder

**Comment by psquizzle** [comment]
I know the library isn't for android yet however, I am unable to build the app with the library installed, also using Expo.

[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Build file '/private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/3029003b-1f2c-4d42-9f0d-12959188b05d/build/node_modules/react-native-cloud-store/android/build.gradle' line: 19
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred evaluating project ':react-native-cloud-store'.
[RUN_GRADLEW] > java.lang.ExceptionInInitializerError (no error message)
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] >
[RUN_GRADLEW] Run with
[RUN_GRADLEW] --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred configuring project ':react-native-cloud-store'.
[RUN_GRADLEW] > compileSdkVersion is not specified. Please add it to build.gradle
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] * Get more help at https://help.gradle.org

Do you have any ideas on how to proceed?

**Comment by XHMM** [comment]
> 
Can you provide a simple reproduce demo?

And you can open a new issue for this problem to keep discussing.  🙂
